
server:
  port: 8080
spring:
  application:
    name: reset-api-shop
  datasource:
    name: vision
    url: jdbc:mysql://127.0.0.1:3306/vision?serverTimezone=GMT%2B8&useSSL=FALSE&useUnicode=true&characterEncoding=utf-8&com.mysql.jdbc.Driver
    username: root
    password: asdf@123456
    #driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
    # 连接超时时间（毫秒）
    timeout: 1500ms
    database: 8
      # 哨兵模式
      #sentinel:
      #master: credit-pbs
    #nodes: 192.168.90.41:26383,192.168.90.42:26383,192.168.90.43:26383
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    properties:
      heartbeat:
        interval:
          ms: 4000
        session:
          timeout:
            ms: 10000
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: "reptile"
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      auto-commit-interval: 6S
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: true
      properties:
        spring:
          json:
            trusted:
              packages: '*'


eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: reset-api-shop

