server:
  port: 8761
spring:
  application:
    name: reset-eureka
eureka:
  server:
    enable-self-preservation: false
  instance:
    #服务注册中心实例的主机名，一般可以是自己的本机ip地址，我的是10.3.99.29
    hostname: reset-eureka
    #preferIpAddress: true
    #这样写eureka服务注册中心会显示本机ip+端口号
    #instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    #这样写eureka服务注册中心会显示项目名和端口号
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    #是否检索服务
    fetch-registry: false
    #默认配置下，eureka会将自己作为客户端，从而尝试将自己也注册到上面去，所以我们在这里配置false,不让它注册
    register-with-eureka: false
    service-url:
      #客户端配置的服务注册中心的地址,指定服务注册中心的位置
      defaultZone: http://127.0.0.1:8761/eureka/