
server:
  port: 8766
spring:
  application:
    name: reset-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
    # 连接超时时间（毫秒）
    timeout: 1500ms
    database: 8
      # 哨兵模式
      #sentinel:
    #master: credit-pbs
    #nodes: 192.168.90.41:26383,192.168.90.42:26383,192.168.90.43:26383

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: reset-gateway


  spring:
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
    CommonsMultipartResolver:
      defaultEncoding: utf-8
      maxUploadSize: 10485760000
      maxInMemorySize: 40960

  #instance:
   # prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    #appname: reset-gateway
