server:
  port: 8072
spring:
  application:
    name: reset-reptile
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    properties:
      heartbeat:
        interval:
          ms: 4000
        session:
          timeout:
            ms: 10000
    producer:
      properties:
        max:
          request:
            size: 300000000
      acks: -1
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: reset-reptile
logging:
  config: classpath:logback.xml
kafka-topic:
  reptile-pages: reptile-pages



